# -*- coding: utf-8 -*-
# BareBones Single-File Web Framework Bundle
# Automatically generated by build.py. Deterministic and reproducible.

# ==========================================================================
# File: barebones/router.py
# ==========================================================================
import json
import re
import urllib.parse

class Request:
    def __init__(self, method, path, headers, query, body, cookies, socket=None):
        self.method = method.upper()
        self.path = path
        self.headers = {k.lower(): v for k, v in headers.items()}
        self.query = query
        self.body = body
        self.cookies = cookies
        self.socket = socket
        self.session = {}  # Decrypted session dict
        self.json = None   # Parsed JSON dict
        self.form = None   # Parsed URL-encoded dict
        self.path_params = {}

class Response:
    STATUS_MAP = {
        101: "Switching Protocols",
        200: "OK",
        201: "Created",
        204: "No Content",
        206: "Partial Content",
        301: "Moved Permanently",
        302: "Found",
        400: "Bad Request",
        401: "Unauthorized",
        403: "Forbidden",
        404: "Not Found",
        405: "Method Not Allowed",
        500: "Internal Server Error",
    }

    def __init__(self, body=b"", status=200, headers=None):
        self.status = status
        self.body = body if isinstance(body, bytes) else body.encode('utf-8')
        self.headers = {}
        if headers:
            for k, v in headers.items():
                self.headers[k.lower()] = str(v)
        self.cookies_to_set = []
        self.file_path = None
        self.file_offset = 0
        self.file_length = None

    def get_body_chunks(self, chunk_size=8192):
        if self.file_path:
            try:
                with open(self.file_path, "rb") as f:
                    if self.file_offset:
                        f.seek(self.file_offset)
                    remaining = self.file_length if self.file_length is not None else float('inf')
                    while remaining > 0:
                        to_read = min(chunk_size, remaining)
                        chunk = f.read(to_read)
                        if not chunk:
                            break
                        yield chunk
                        remaining -= len(chunk)
            except Exception:
                yield b""
        else:
            yield self.body

    def set_header(self, name, value):
        self.headers[name.lower()] = str(value)

    def set_cookie(self, name, value, max_age=None, expires=None, path="/", domain=None, secure=False, httponly=False, samesite="Lax"):
        cookie = f"{name}={value}"
        if max_age is not None:
            cookie += f"; Max-Age={max_age}"
        if expires is not None:
            cookie += f"; Expires={expires}"
        if path:
            cookie += f"; Path={path}"
        if domain:
            cookie += f"; Domain={domain}"
        if secure:
            cookie += "; Secure"
        if httponly:
            cookie += "; HttpOnly"
        if samesite:
            cookie += f"; SameSite={samesite}"
        self.cookies_to_set.append(cookie)

    def delete_cookie(self, name, path="/", domain=None):
        self.set_cookie(name, "", max_age=0, expires="Thu, 01 Jan 1970 00:00:00 GMT", path=path, domain=domain)

    @classmethod
    def json(cls, data, status=200, headers=None):
        body = json.dumps(data).encode('utf-8')
        resp = cls(body, status, headers)
        resp.set_header("Content-Type", "application/json")
        return resp

    @classmethod
    def html(cls, html_content, status=200, headers=None):
        body = html_content.encode('utf-8') if isinstance(html_content, str) else html_content
        resp = cls(body, status, headers)
        resp.set_header("Content-Type", "text/html; charset=utf-8")
        return resp

    @classmethod
    def text(cls, text_content, status=200, headers=None):
        body = text_content.encode('utf-8') if isinstance(text_content, str) else text_content
        resp = cls(body, status, headers)
        resp.set_header("Content-Type", "text/plain; charset=utf-8")
        return resp

class Router:
    def __init__(self):
        self.routes = []

    def add_route(self, method, path, handler):
        # Escape regex special characters, except '<' and '>'
        pattern = ""
        in_tag = False
        for char in path:
            if char == '<':
                in_tag = True
                pattern += char
            elif char == '>':
                in_tag = False
                pattern += char
            else:
                if in_tag:
                    pattern += char
                else:
                    pattern += re.escape(char)
        
        # Replace tags in a single pass to prevent nested substitution bugs
        def replace_tag(match):
            tag = match.group(1)
            if tag.startswith("path:"):
                return f"(?P<{tag[5:]}>.+)"
            return f"(?P<{tag}>[^/]+)"

        pattern = re.sub(r'<([^>]+)>', replace_tag, pattern)
        
        regex = re.compile("^" + pattern + "$")
        self.routes.append((method.upper(), regex, handler, path))

    def match(self, method, path):
        for r_method, r_regex, handler, r_path in self.routes:
            if r_method == method:
                m = r_regex.match(path)
                if m:
                    return handler, m.groupdict()
        return None, None



# ==========================================================================
# File: barebones/websocket.py
# ==========================================================================
import hashlib
import base64
import struct

WEBSOCKET_GUID = "258EAFA5-E914-47DA-95CA-C5AB0DC85B11"

def calculate_accept_key(sec_key):
    concat = sec_key + WEBSOCKET_GUID
    sha1 = hashlib.sha1(concat.encode('utf-8')).digest()
    return base64.b64encode(sha1).decode('utf-8')

class WebSocketConnection:
    def __init__(self, sock):
        self.sock = sock
        self.closed = False

    def send_message(self, message, opcode=1):
        """
        Sends a WebSocket frame to the client.
        opcode 1 is Text, opcode 2 is Binary.
        """
        if self.closed:
            return
        
        payload = message.encode('utf-8') if isinstance(message, str) else message
        length = len(payload)
        
        # Byte 1: FIN = 1, RSV = 0, Opcode
        header = bytearray([0x80 | opcode])
        
        # Byte 2: Mask = 0 (server to client must be unmasked), Payload length
        if length < 126:
            header.append(length)
        elif length < 65536:
            header.append(126)
            header.extend(struct.pack("!H", length))
        else:
            header.append(127)
            header.extend(struct.pack("!Q", length))
            
        try:
            self.sock.sendall(header + payload)
        except Exception:
            self.closed = True

    def recv_message(self):
        """
        Reads and decodes a single frame from the client.
        Blocks until a complete message is received, or connection closes.
        """
        if self.closed:
            return None
            
        try:
            # Read first 2 bytes: FIN/Opcode (1B), Mask/Len (1B)
            header = self._read_exact(2)
            if not header:
                return None
                
            fin = (header[0] & 0x80) != 0
            opcode = header[0] & 0x0f
            
            masked = (header[1] & 0x80) != 0
            payload_len = header[1] & 0x7f
            
            if payload_len == 126:
                len_bytes = self._read_exact(2)
                if not len_bytes:
                    return None
                payload_len = struct.unpack("!H", len_bytes)[0]
            elif payload_len == 127:
                len_bytes = self._read_exact(8)
                if not len_bytes:
                    return None
                payload_len = struct.unpack("!Q", len_bytes)[0]
                
            masking_key = b""
            if masked:
                masking_key = self._read_exact(4)
                if not masking_key:
                    return None
                    
            payload = self._read_exact(payload_len)
            if payload is None:
                return None
                
            if masked:
                # Unmask payload
                payload = bytes(b ^ masking_key[i % 4] for i, b in enumerate(payload))
                
            if opcode == 8: # Connection Close
                self.close()
                return None
            elif opcode == 9: # Ping
                # Respond with Pong
                self.send_message(payload, opcode=10)
                return self.recv_message() # read next message
            elif opcode == 10: # Pong
                return self.recv_message() # read next message
            elif opcode == 1: # Text
                return payload.decode('utf-8')
            elif opcode == 2: # Binary
                return payload
            else:
                return payload # Fallback
                
        except Exception:
            self.closed = True
            return None

    def _read_exact(self, n):
        data = bytearray()
        while len(data) < n:
            packet = self.sock.recv(n - len(data))
            if not packet:
                return None
            data.extend(packet)
        return bytes(data)

    def close(self):
        if not self.closed:
            self.closed = True
            try:
                # Send close frame
                self.sock.sendall(bytearray([0x80 | 8, 0]))
                self.sock.close()
            except Exception:
                pass



# ==========================================================================
# File: barebones/sessions.py
# ==========================================================================
import hmac
import hashlib
import json
import base64
import copy

def sign_session(session_dict, secret_key):
    # Serialize to JSON and encode to base64
    json_bytes = json.dumps(session_dict).encode('utf-8')
    b64_str = base64.b64encode(json_bytes).decode('utf-8')
    # Sign base64 payload
    sig = hmac.new(secret_key.encode('utf-8'), b64_str.encode('utf-8'), hashlib.sha256).hexdigest()
    return f"{b64_str}.{sig}"

def verify_session(cookie_value, secret_key):
    if not cookie_value:
        return {}
    try:
        parts = cookie_value.split('.', 1)
        if len(parts) != 2:
            return {}
        b64_str, sig = parts
        # Verify HMAC-SHA256 signature
        expected_sig = hmac.new(secret_key.encode('utf-8'), b64_str.encode('utf-8'), hashlib.sha256).hexdigest()
        if not hmac.compare_digest(sig, expected_sig):
            return {}
        # Decode base64 and parse JSON
        json_bytes = base64.b64decode(b64_str.encode('utf-8'))
        return json.loads(json_bytes.decode('utf-8'))
    except Exception:
        return {}

def session_middleware(secret_key, session_cookie_name="session"):
    def middleware(req, next_fn):
        # 1. Load session from cookie
        cookie_val = req.cookies.get(session_cookie_name, "")
        req.session = verify_session(cookie_val, secret_key)
        
        # Keep copy of original session state to see if it changes
        original_session = copy.deepcopy(req.session)
        
        # 2. Process request
        resp = next_fn(req)
        
        # 3. If session changed, sign and set new cookie
        if req.session != original_session:
            new_cookie_val = sign_session(req.session, secret_key)
            resp.set_cookie(session_cookie_name, new_cookie_val, httponly=True, samesite="Lax")
            
        return resp
    return middleware



# ==========================================================================
# File: barebones/middleware.py
# ==========================================================================
import time
import gzip
import json
import urllib.parse

class MiddlewareChain:
    def __init__(self):
        self.middlewares = []

    def add(self, middleware_func):
        self.middlewares.append(middleware_func)

    def execute(self, request, final_handler):
        def make_next(index):
            if index < len(self.middlewares):
                current_mw = self.middlewares[index]
                return lambda req: current_mw(req, make_next(index + 1))
            else:
                return final_handler
        return make_next(0)(request)

def logger_middleware(req, next_fn):
    start = time.time()
    resp = next_fn(req)
    duration = (time.time() - start) * 1000
    print(f"[{req.method}] {req.path} -> {resp.status} ({duration:.2f}ms)")
    return resp

def cors_middleware(allowed_origins="*", allowed_methods="GET, POST, PUT, DELETE, OPTIONS", allowed_headers="Content-Type, Authorization, Cookie"):
    def middleware(req, next_fn):
        if req.method == "OPTIONS":
            resp = Response(status=204)
            resp.set_header("Access-Control-Allow-Origin", allowed_origins)
            resp.set_header("Access-Control-Allow-Methods", allowed_methods)
            resp.set_header("Access-Control-Allow-Headers", allowed_headers)
            resp.set_header("Access-Control-Allow-Credentials", "true")
            return resp
        
        resp = next_fn(req)
        resp.set_header("Access-Control-Allow-Origin", allowed_origins)
        resp.set_header("Access-Control-Allow-Methods", allowed_methods)
        resp.set_header("Access-Control-Allow-Headers", allowed_headers)
        resp.set_header("Access-Control-Allow-Credentials", "true")
        return resp
    return middleware

def json_parser_middleware(req, next_fn):
    content_type = req.headers.get("content-type", "")
    if "application/json" in content_type and req.body:
        try:
            req.json = json.loads(req.body.decode('utf-8'))
        except Exception:
            return Response.json({"error": "Invalid JSON"}, status=400)
    return next_fn(req)

def form_parser_middleware(req, next_fn):
    content_type = req.headers.get("content-type", "")
    if "application/x-www-form-urlencoded" in content_type and req.body:
        try:
            req.form = dict(urllib.parse.parse_qsl(req.body.decode('utf-8')))
        except Exception:
            return Response.json({"error": "Invalid form data"}, status=400)
    return next_fn(req)

def gzip_middleware(req, next_fn):
    resp = next_fn(req)
    
    # Check if gzip is accepted
    accept_encoding = req.headers.get("accept-encoding", "")
    if "gzip" not in accept_encoding:
        return resp
        
    content_type = resp.headers.get("content-type", "")
    if not resp.body or len(resp.body) < 100:
        return resp
        
    # Check eligibility (text files, json, HTML, scripts)
    eligible_types = ["text/", "json", "javascript", "xml"]
    if not any(t in content_type for t in eligible_types):
        return resp
        
    if "content-encoding" in resp.headers:
        return resp
        
    try:
        compressed = gzip.compress(resp.body)
        if len(compressed) < len(resp.body):
            resp.body = compressed
            resp.set_header("Content-Encoding", "gzip")
            resp.set_header("Content-Length", str(len(compressed)))
    except Exception:
        pass
        
    return resp

import threading

class TokenBucket:
    def __init__(self, capacity, rate):
        self.capacity = float(capacity)
        self.rate = float(rate)
        self.tokens = float(capacity)
        self.last_update = time.time()
        self.lock = threading.Lock()

    def consume(self):
        with self.lock:
            now = time.time()
            elapsed = now - self.last_update
            self.last_update = now
            self.tokens = min(self.capacity, self.tokens + elapsed * self.rate)
            if self.tokens >= 1.0:
                self.tokens -= 1.0
                return True, 0.0
            # Compute wait time for 1 token
            needed = 1.0 - self.tokens
            wait_time = needed / self.rate
            return False, wait_time

class RateLimiter:
    def __init__(self, capacity, rate):
        self.capacity = capacity
        self.rate = rate
        self.buckets = {}
        self.lock = threading.Lock()

    def get_bucket(self, ip):
        with self.lock:
            if ip not in self.buckets:
                self.buckets[ip] = TokenBucket(self.capacity, self.rate)
            return self.buckets[ip]

def rate_limit_middleware(capacity=10, rate=5.0):
    limiter = RateLimiter(capacity, rate)
    def middleware(req, next_fn):
        ip = "127.0.0.1"
        if req.socket:
            try:
                ip = req.socket.getpeername()[0]
            except Exception:
                pass
                
        # Skip rate limiter for WebSockets, Telemetry streaming, or if bypass header is present
        if "x-bypass-rate-limit" in req.headers or req.headers.get("upgrade", "").lower() == "websocket" or req.path == "/api/telemetry":
            return next_fn(req)
            
        bucket = limiter.get_bucket(ip)
        allowed, wait_time = bucket.consume()
        if not allowed:
            resp = Response.json(
                {"error": "Too Many Requests", "retry_after": round(wait_time, 2)},
                status=429
            )
            resp.set_header("Retry-After", str(max(1, int(wait_time))))
            return resp
            
        return next_fn(req)
    return middleware




# ==========================================================================
# File: barebones/static.py
# ==========================================================================
import os
import mimetypes

def parse_range_header(range_header, file_size):
    """
    Parses Range headers like 'bytes=0-1024' or 'bytes=500-'.
    Returns (start, end) or None.
    """
    if not range_header or not range_header.startswith("bytes="):
        return None
    val = range_header.split("bytes=", 1)[1].strip()
    if not val:
        return None
        
    # We only handle single range requests
    if "," in val:
        val = val.split(",")[0].strip()
        
    try:
        if val.startswith("-"):
            suffix_len = int(val[1:])
            start = max(0, file_size - suffix_len)
            end = file_size - 1
        elif val.endswith("-"):
            start = int(val[:-1])
            end = file_size - 1
        else:
            parts = val.split("-")
            start = int(parts[0])
            end = int(parts[1])
            
        if start >= file_size or start > end:
            return None
        end = min(end, file_size - 1)
        return start, end
    except ValueError:
        return None

def serve_static(static_dir):
    """
    Returns a route handler that serves files from static_dir.
    Matches route param 'filepath'.
    """
    def handler(req, **kwargs):
        filepath = kwargs.get("filepath", "")
        # Sanitize path to prevent directory traversal
        normalized = os.path.normpath(filepath)
        if normalized.startswith("..") or os.path.isabs(normalized):
            return Response(b"Forbidden", status=403)
            
        full_path = os.path.join(static_dir, normalized)
        if not os.path.exists(full_path) or os.path.isdir(full_path):
            return Response(b"Not Found", status=404)
            
        mime_type, _ = mimetypes.guess_type(full_path)
        if not mime_type:
            mime_type = "application/octet-stream"
            
        file_size = os.path.getsize(full_path)
        range_header = req.headers.get("range", "")
        parsed_range = parse_range_header(range_header, file_size)
        
        if parsed_range:
            start, end = parsed_range
            content_length = end - start + 1
            resp = Response(status=206)
            resp.file_path = full_path
            resp.file_offset = start
            resp.file_length = content_length
            resp.set_header("Content-Type", mime_type)
            resp.set_header("Content-Length", str(content_length))
            resp.set_header("Content-Range", f"bytes {start}-{end}/{file_size}")
            resp.set_header("Accept-Ranges", "bytes")
            return resp
        else:
            resp = Response(status=200)
            resp.file_path = full_path
            resp.file_offset = 0
            resp.file_length = file_size
            resp.set_header("Content-Type", mime_type)
            resp.set_header("Content-Length", str(file_size))
            resp.set_header("Accept-Ranges", "bytes")
            return resp
            
    return handler



# ==========================================================================
# File: barebones/server.py
# ==========================================================================
import socket
import threading
import selectors
import urllib.parse
import time

class ConnectionState:
    def __init__(self, sock):
        self.sock = sock
        self.read_buffer = bytearray()
        self.write_buffer = bytearray()
        self.request = None
        self.request_body_acc = bytearray()
        self.response = None
        self.response_generator = None
        self.last_activity = time.time()

class BareBones:
    def __init__(self, secret_key="barebones_secret"):
        self.router = Router()
        self.ws_router = Router()
        self.middleware = MiddlewareChain()
        self.secret_key = secret_key
        self.concurrency_mode = "threaded"
        self.running = False
        self.server_sock = None
        self._mode_changed = False
        self.selector = None

        # Register default body parser and session middlewares
        self.middleware.add(rate_limit_middleware(capacity=15, rate=3.0)) # 15 tokens capacity, 3 refills per sec
        self.middleware.add(json_parser_middleware)
        self.middleware.add(form_parser_middleware)
        self.middleware.add(session_middleware(secret_key))
        self.middleware.add(gzip_middleware)

    def get(self, path):
        def decorator(handler):
            self.router.add_route("GET", path, handler)
            return handler
        return decorator

    def post(self, path):
        def decorator(handler):
            self.router.add_route("POST", path, handler)
            return handler
        return decorator

    def put(self, path):
        def decorator(handler):
            self.router.add_route("PUT", path, handler)
            return handler
        return decorator

    def delete(self, path):
        def decorator(handler):
            self.router.add_route("DELETE", path, handler)
            return handler
        return decorator

    def websocket(self, path):
        def decorator(handler):
            self.ws_router.add_route("GET", path, handler)
            return handler
        return decorator

    def run(self, host="127.0.0.1", port=8080, mode="threaded"):
        self.concurrency_mode = mode
        self.running = True
        
        while self.running:
            self._mode_changed = False
            self.server_sock = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
            self.server_sock.setsockopt(socket.SOL_SOCKET, socket.SO_REUSEADDR, 1)
            try:
                self.server_sock.bind((host, port))
                self.server_sock.listen(128)
                print(f"[*] BareBones running at http://{host}:{port}/ in {self.concurrency_mode.upper()} mode")
            except Exception as e:
                print(f"[!] Bind failed on {host}:{port}: {e}")
                break

            if self.concurrency_mode == "threaded":
                self._run_threaded()
            else:
                self._run_eventloop()

            if not self._mode_changed:
                break

    def toggle_mode(self, new_mode):
        if new_mode in ["threaded", "eventloop"] and new_mode != self.concurrency_mode:
            print(f"[*] Switching concurrency mode to {new_mode.upper()}...")
            self.concurrency_mode = new_mode
            self._mode_changed = True
            if self.server_sock:
                try:
                    self.server_sock.close()
                except Exception:
                    pass
            if self.selector:
                try:
                    self.selector.close()
                except Exception:
                    pass

    def _run_threaded(self):
        self.server_sock.settimeout(0.1)
        while self.running and not self._mode_changed:
            try:
                client_sock, addr = self.server_sock.accept()
            except socket.timeout:
                continue
            except Exception:
                break

            t = threading.Thread(target=handle_client_sync, args=(client_sock, self), daemon=True)
            t.start()

    def _run_eventloop(self):
        self.selector = selectors.DefaultSelector()
        self.server_sock.setblocking(False)
        self.selector.register(self.server_sock, selectors.EVENT_READ, data="accept")

        while self.running and not self._mode_changed:
            now = time.time()
            try:
                for fd, key in list(self.selector.get_map().items()):
                    if key.data != "accept":
                        state = key.data
                        if state.request is None and not state.write_buffer:
                            if now - state.last_activity > 5.0:
                                self.close_connection(state)
            except Exception:
                pass

            try:
                events = self.selector.select(timeout=1.0)
            except Exception:
                break

            for key, mask in events:
                if key.data == "accept":
                    try:
                        client_sock, addr = self.server_sock.accept()
                        client_sock.setblocking(False)
                        state = ConnectionState(client_sock)
                        self.selector.register(client_sock, selectors.EVENT_READ, data=state)
                    except Exception:
                        pass
                else:
                    state = key.data
                    if mask & selectors.EVENT_READ:
                        self.process_read(state)
                    if mask & selectors.EVENT_WRITE:
                        self.process_write(state)

        # Close all selector registrations
        try:
            self.selector.close()
        except Exception:
            pass

    def close_connection(self, state):
        try:
            self.selector.unregister(state.sock)
        except Exception:
            pass
        try:
            state.sock.close()
        except Exception:
            pass

    def finish_response(self, state):
        keep_alive = getattr(state.request, "keep_alive", False)
        if keep_alive and self.running:
            state.read_buffer = bytearray()
            state.request = None
            state.request_body_acc = bytearray()
            state.response = None
            state.response_generator = None
            try:
                self.selector.modify(state.sock, selectors.EVENT_READ, data=state)
            except Exception:
                self.close_connection(state)
        else:
            self.close_connection(state)

    def process_read(self, state):
        state.last_activity = time.time()
        try:
            chunk = state.sock.recv(4096)
        except (BlockingIOError, InterruptedError):
            return
        except Exception:
            self.close_connection(state)
            return

        if not chunk:
            self.close_connection(state)
            return

        if not state.request:
            state.read_buffer.extend(chunk)
            if b"\r\n\r\n" in state.read_buffer:
                parts = state.read_buffer.split(b"\r\n\r\n", 1)
                header_bytes = parts[0]
                body_bytes = parts[1]
                
                req = parse_request_headers(header_bytes, state.sock)
                if not req:
                    self.close_connection(state)
                    return
                state.request = req
                state.request_body_acc.extend(body_bytes)
        else:
            state.request_body_acc.extend(chunk)

        if state.request:
            content_length = int(state.request.headers.get("content-length", 0))
            if len(state.request_body_acc) >= content_length:
                state.request.body = bytes(state.request_body_acc[:content_length])
                parse_request_cookies_and_body(state.request)

                # Check WS upgrade
                if state.request.headers.get("upgrade", "").lower() == "websocket" and self.ws_router:
                    ws_handler, ws_path_params = self.ws_router.match(state.request.method, state.request.path)
                    if ws_handler:
                        try:
                            self.selector.unregister(state.sock)
                        except Exception:
                            pass
                        state.sock.setblocking(True)
                        handle_ws_upgrade(state.sock, state.request, ws_handler, ws_path_params)
                        return

                handler, path_params = self.router.match(state.request.method, state.request.path)
                if not handler:
                    resp = Response(b"Not Found", status=404)
                else:
                    state.request.path_params = path_params
                    final_handler = lambda r: handler(r, **r.path_params)
                    resp = self.middleware.execute(state.request, final_handler)

                if getattr(resp, "hijacked", False):
                    try:
                        self.selector.unregister(state.sock)
                    except Exception:
                        pass
                    return

                state.response = resp
                status_text = Response.STATUS_MAP.get(resp.status, "Unknown")
                res_lines = [f"HTTP/1.1 {resp.status} {status_text}"]
                
                # Setup Connection Persistence headers
                keep_alive = getattr(state.request, "keep_alive", False)
                if keep_alive:
                    resp.set_header("Connection", "keep-alive")
                    resp.set_header("Keep-Alive", "timeout=5, max=100")
                else:
                    resp.set_header("Connection", "close")

                if "content-length" not in resp.headers and not resp.file_path:
                    resp.set_header("Content-Length", str(len(resp.body)))
                for k, v in resp.headers.items():
                    res_lines.append(f"{k.title()}: {v}")
                for cookie in resp.cookies_to_set:
                    res_lines.append(f"Set-Cookie: {cookie}")
                res_lines.append("")
                res_lines.append("")

                state.write_buffer.extend("\r\n".join(res_lines).encode('utf-8'))
                state.response_generator = resp.get_body_chunks()
                self.selector.modify(state.sock, selectors.EVENT_WRITE, data=state)

    def process_write(self, state):
        state.last_activity = time.time()
        if not state.write_buffer:
            if state.response_generator:
                try:
                    chunk = next(state.response_generator)
                    state.write_buffer.extend(chunk)
                except StopIteration:
                    self.finish_response(state)
                    return
                except Exception:
                    self.close_connection(state)
                    return
            else:
                self.finish_response(state)
                return

        try:
            sent = state.sock.send(state.write_buffer)
            state.write_buffer = state.write_buffer[sent:]
        except (BlockingIOError, InterruptedError):
            pass
        except Exception:
            self.close_connection(state)

def parse_request_headers(header_bytes, sock):
    try:
        header_lines = header_bytes.decode('utf-8', errors='ignore').split('\r\n')
        if not header_lines or not header_lines[0]:
            return None
        req_line = header_lines[0].split(' ')
        if len(req_line) < 2:
            return None
        method, full_path = req_line[0], req_line[1]

        path = full_path
        query = {}
        if '?' in full_path:
            path, query_str = full_path.split('?', 1)
            for pair in query_str.split('&'):
                if '=' in pair:
                    k, v = pair.split('=', 1)
                    query[urllib.parse.unquote(k)] = urllib.parse.unquote(v)
                elif pair:
                    query[urllib.parse.unquote(pair)] = ""

        headers = {}
        for line in header_lines[1:]:
            if not line:
                continue
            if ':' in line:
                k, v = line.split(':', 1)
                headers[k.strip().lower()] = v.strip()

        version = req_line[2] if len(req_line) > 2 else "HTTP/1.1"
        conn_header = headers.get("connection", "").lower()
        if "1.1" in version:
            keep_alive = conn_header != "close"
        else:
            keep_alive = conn_header == "keep-alive"

        req = Request(method, path, headers, query, b"", {}, sock)
        req.keep_alive = keep_alive
        return req
    except Exception:
        return None

def parse_request_cookies_and_body(req):
    cookie_hdr = req.headers.get("cookie", "")
    cookies = {}
    if cookie_hdr:
        for item in cookie_hdr.split(';'):
            if '=' in item:
                k, v = item.split('=', 1)
                cookies[k.strip()] = v.strip()
    req.cookies = cookies

def handle_client_sync(client_sock, app):
    client_sock.settimeout(5.0)  # Keep-alive idle timeout
    upgraded = False
    try:
        while app.running:
            req = parse_request_sync(client_sock)
            if not req:
                break
            
            # Check WS upgrade
            if req.headers.get("upgrade", "").lower() == "websocket" and app.ws_router:
                ws_handler, ws_path_params = app.ws_router.match(req.method, req.path)
                if ws_handler:
                    upgraded = True
                    handle_ws_upgrade(client_sock, req, ws_handler, ws_path_params)
                    return

            handler, path_params = app.router.match(req.method, req.path)
            if not handler:
                resp = Response(b"Not Found", status=404)
            else:
                req.path_params = path_params
                final_handler = lambda r: handler(r, **r.path_params)
                resp = app.middleware.execute(req, final_handler)

            if getattr(resp, "hijacked", False):
                upgraded = True
                return

            keep_alive = getattr(req, "keep_alive", False)
            if keep_alive:
                resp.set_header("Connection", "keep-alive")
                resp.set_header("Keep-Alive", "timeout=5, max=100")
            else:
                resp.set_header("Connection", "close")

            send_response_sync(client_sock, resp)

            if not keep_alive:
                break
    except socket.timeout:
        pass
    except Exception as e:
        print("[!] Thread error:", e)
        try:
            send_response_sync(client_sock, Response(b"Internal Server Error", status=500))
        except Exception:
            pass
    finally:
        if not upgraded:
            try:
                client_sock.close()
            except Exception:
                pass

def parse_request_sync(client_sock):
    buffer = bytearray()
    while b"\r\n\r\n" not in buffer:
        chunk = client_sock.recv(4096)
        if not chunk:
            break
        buffer.extend(chunk)
    if not buffer:
        return None

    parts = buffer.split(b"\r\n\r\n", 1)
    header_bytes = parts[0]
    body_buffer = bytearray(parts[1]) if len(parts) > 1 else bytearray()

    req = parse_request_headers(header_bytes, client_sock)
    if not req:
        return None

    content_length = int(req.headers.get("content-length", 0))
    while len(body_buffer) < content_length:
        chunk = client_sock.recv(4096)
        if not chunk:
            break
        body_buffer.extend(chunk)

    req.body = bytes(body_buffer[:content_length])
    parse_request_cookies_and_body(req)
    return req

def send_response_sync(client_sock, resp):
    status_text = Response.STATUS_MAP.get(resp.status, "Unknown")
    res_lines = [f"HTTP/1.1 {resp.status} {status_text}"]

    if "content-length" not in resp.headers and not resp.file_path:
        resp.set_header("Content-Length", str(len(resp.body)))

    for k, v in resp.headers.items():
        res_lines.append(f"{k.title()}: {v}")

    for cookie in resp.cookies_to_set:
        res_lines.append(f"Set-Cookie: {cookie}")

    res_lines.append("")
    res_lines.append("")

    header_bytes = "\r\n".join(res_lines).encode('utf-8')
    client_sock.sendall(header_bytes)

    for chunk in resp.get_body_chunks():
        client_sock.sendall(chunk)

def handle_ws_upgrade(client_sock, req, ws_handler, ws_path_params):
    sec_key = req.headers.get("sec-websocket-key", "")
    if not sec_key:
        try:
            send_response_sync(client_sock, Response(b"Missing Sec-WebSocket-Key", status=400))
        except Exception:
            pass
        return

    accept_key = calculate_accept_key(sec_key)
    res_lines = [
        "HTTP/1.1 101 Switching Protocols",
        "Upgrade: websocket",
        "Connection: Upgrade",
        f"Sec-WebSocket-Accept: {accept_key}",
        "",
        ""
    ]
    header_bytes = "\r\n".join(res_lines).encode('utf-8')
    client_sock.sendall(header_bytes)

    ws_conn = WebSocketConnection(client_sock)
    def run_ws():
        try:
            ws_handler(ws_conn, **ws_path_params)
        except Exception as e:
            print("[!] WebSocket handler error:", e)
        finally:
            ws_conn.close()

    t = threading.Thread(target=run_ws, daemon=True)
    t.start()
