import os
import re

def build_single_file():
    files_in_order = [
        "barebones/router.py",
        "barebones/websocket.py",
        "barebones/sessions.py",
        "barebones/middleware.py",
        "barebones/static.py",
        "barebones/server.py"
    ]
    
    combined_lines = [
        '# -*- coding: utf-8 -*-',
        '# BareBones Single-File Web Framework Bundle',
        '# Automatically generated by build.py. Deterministic and reproducible.',
        ''
    ]
    
    # We will gather all standard library imports to place at the top for clean code,
    # or we can keep them inline but remove local relative imports. Removing local imports is simpler
    # and less error-prone if we just filter them out.
    # Local imports to remove: e.g., "from .router import ...", "from .websocket import ...", etc.
    local_import_pattern = re.compile(r'^\s*(from\s+\.(router|websocket|sessions|middleware|static|server)\s+import|from\s+barebones\s+import|from\s+\.\s+import)')
    
    for filepath in files_in_order:
        if not os.path.exists(filepath):
            print(f"[!] Error: File not found {filepath}")
            return False
            
        combined_lines.append(f"# ==========================================================================")
        combined_lines.append(f"# File: {filepath}")
        combined_lines.append(f"# ==========================================================================")
        
        with open(filepath, "r", encoding="utf-8") as f:
            content = f.read()
            # Normalize line endings to \n
            content = content.replace("\r\n", "\n")
            
            lines = content.split("\n")
            for line in lines:
                if local_import_pattern.match(line):
                    # Skip local relative imports
                    continue
                combined_lines.append(line)
        
        combined_lines.append("")
        combined_lines.append("")

    # Join and write deterministically
    output_content = "\n".join(combined_lines)
    
    # Ensure there is exactly one trailing newline
    output_content = output_content.rstrip() + "\n"
    
    output_path = "barebones_single.py"
    with open(output_path, "w", encoding="utf-8") as f:
        f.write(output_content)
        
    print(f"[*] Successfully generated reproducible single-file bundle: {output_path}")
    print(f"[*] Bundle Size: {len(output_content)} bytes")
    return True

if __name__ == "__main__":
    build_single_file()
